@UserService_HostAddress = http://localhost:5000/api
@Access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDAzMzE2MTAyOTMwMzY2NDY0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImp0aSI6IjcwMDhlNDMwLTZlY2ItNGQ5OC04ZjIxLWRjYTA4ODI2ZGEzOSIsImV4cCI6MTc1NDg0ODQyNiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.P2u2ooU9cOzOV28FBsCZ0l4JD2qcvEHKY8EszMNEQ_U

POST {{UserService_HostAddress}}/shortener
Content-Type: application/json
Authorization: Bearer {{Access_token}}

{
  "originalUrl": "https://google.com"
}

###

DELETE {{UserService_HostAddress}}/shortener
Content-Type: application/json
Authorization: Bearer {{Access_token}}

{
  "originalUrl": "https://google.com"
}

###
